version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tareasdb
    ports:
      - "3306:3306"

  springapp:
    build: .
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
